#ifndef BRICKBREAKER_MACROS_H
#define BRICKBREAKER_MACROS_H

#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 1000

#define PLAYER_WIDTH 150
#define PLAYER_HEIGHT 20
#define PLAYER_SPACE_FROM_BOTTOM 20
#define PLAYER_ACCELERATION 3
#define PLAYER_MAX_SPEED 10
#define PLAYER_RESISTANCE 0.3
#define PLAYER_GRAVITY 4
#define PLAYER_TEXTURE "./textures/hit2.bmp"

#define BALL_WIDTH 25
#define BALL_HEIGHT 25
#define BALL_GRAVITY 0.5
#define BALL_MAX_SPEED 15
#define BALL_SPEED_GAIN 0.25
#define BALL_BOUNCE_BOOST 0.6

#define BRICK_ROWS 3
#define BRICK_COLUMNS 8
#define BRICK_HEIGHT 80
#define VERTICAL_SPACE_BETWEEN_BRICKS 30
#define HORIZONTAL_SPACE_BETWEEN_BRICKS 30
#define SPACE_FROM_SCREEN_TOP 20


#endif //BRICKBREAKER_MACROS_H
